Allow libgit2 to guess sysdir homedir successfully (bsc#1250520) (bsc#1227207) (#731)
* Allow libgit2 to guess sysdir homedir successfully

This prevents the generic error:

_pygit2.GitError: error loading known_hosts:

which is happening in certain pygit2/libgit2 versions

* Fix pygit2 unit test to check HOME is injected