Removes Beacon configuration Deprecation Warning (#48)
The message "DeprecationWarning: Beacon configuration should be a list
instead of a dictionary." was shown on the console if any beacon was defined
not using lists.

This was incompatible with beacon cfg loaders, namely inotify, that was not yet
upgraded to support this change, causing an error whenever a list definition was
used:

File "/usr/lib/python2.7/site-packages/salt/beacons/inotify.py", line 247
TypeError: list indices must be integers, not dict.,
On same file we can read the comment:
"Configuration for inotify beacon should be a dict of dicts"

This commit removes the deprecation message as per @isbm suggestion.